### ISSUE TITLE
Kaj ne dela

### ISSUE THREAD

**Issue by kkac26** [cola9/JazGobar#2]
-Uporabnik lahko doda nepopolno gobo (brez imena in hashtaga)
-Mapa se odpre vedno na isti lokaciji in ne tam kjer se uporabnik nahaja. Dobro bi bilo označiti uporabnikovo lokacijo z nekim drugim markerjem.
-Ob zagonu aplikacija ne upošteva filtrov
-Gobi ne gre spremeniti imena, ampak samo hashtag

**Comment by cola9** [comment]
**Popravil:**
 - Uporabnik ne more dodati nepopolne gobe (brez imena in hashtaga)
 - Mapa se odpre na trenutni lokaciji oz. kjer se uporabnik nahaja. Uporabnikova lokacija označena z drugim markerjem.
 - Ob zagonu aplikacija upošteva filtre
 - Gobi lahko spremenimo ime
 - dodane oz. izboljšane ikone
 - dodane prave slike gob v testne podatke
 - za vsako gobo lahko dobimo navodila za pot do nje preko google maps
 - v seznamu prikaže pri vsak igobe prikaže le tiste hastage ki so na tej lokaciji

**Izboljšal:**
 - Vizualni izgled aplikacije
